### ISSUE TITLE
DB connection being rejected

### ISSUE THREAD

**Issue by verdverm** [bluesky-social/ozone#75]
Hi, first off, thanks for making this awesome service open source! I'm really liking the ATProto paradigm

I'm having issues getting Ozone up in Kubernetes. The database connection appears to be rejected with the following error from the Ozone container.

I've verified the uname/pword do work with the `psql` client

```
kubectl logs -n bsky -f pod/ozone-84df5c9966-kh8vq
error: pg_hba.conf rejects connection for host "10.28.0.40", user "ts", database "ozone", no encryption
    at /usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:86974:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresDriver.acquireConnection (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:119099:20)
    at async RuntimeDriver.acquireConnection (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:117251:24)
    at async DefaultConnectionProvider.provideConnection (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:117174:24)
    at async DefaultQueryExecutor.executeQuery (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:114387:12)
    at async SelectQueryBuilder.execute (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:113294:20)
    at async PostgresIntrospector.getTables (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:119025:24)
    at async #doesTableExists (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:118841:20)
    at async #ensureMigrationTableExists (/usr/src/ozone/node_modules/@atproto/ozone/dist/index.js:118800:10) {
  length: 159,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '468',
  routine: 'ClientAuthentication'
}
```

The Kubernetes manifest

```yaml
apiVersion: v1
kind: List
items:
  - apiVersion: acid.zalan.do/v1
    kind: postgresql
    metadata:
      name: psql
      namespace: bsky
      labels:
        team: acid
    spec:
      teamId: acid
      volume:
        size: 2Gi
      numberOfInstances: 1
      users:
        zalando:
          - superuser
          - createdb
        ts:
          - login
      databases:
        ozone: ts
      postgresql:
        version: "15"
        parameters:
          password_encryption: scram-sha-256
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ozone
      namespace: bsky
      labels:
        app: ozone
    spec:
      selector:
        matchLabels:
          app: ozone
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      minReadySeconds: 5
      template:
        metadata:
          labels:
            app: ozone
        spec:
          containers:
            - name: ozone
              image: ghcr.io/bluesky-social/ozone:0.1.3
              imagePullPolicy: Always
              env:
                - name: NODE_ENV
                  value: production
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ts.psql.credentials.postgresql.acid.zalan.do
                      key: password
                - name: OZONE_DB_POSTGRES_URL
                  value: postgresql://ts:$(DATABASE_PASSWORD)@psql:5432/ozone
                - name: OZONE_PUBLIC_URL
                  value: https://ozone.topicalsource.com
                - name: OZONE_DID_PLC_URL
                  value: https://plc.directory
                - name: OZONE_APPVIEW_URL
                  value: https://api.bsky.app
                - name: OZONE_APPVIEW_DID
                  value: did:web:api.bsky.app
                - name: OZONE_DB_MIGRATE
                  value: "1"
                - name: LOG_ENABLED
                  value: "1"
              envFrom:
                - secretRef:
                    name: ozone-env
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
              ports:
                - containerPort: 3000
                  protocol: TCP
          volumes:
            - name: ozone-env
              secret:
                secretName: ozone-env
```
